function [BW,maskedImage] = floodFillFromPt(RGB, xy,tolerance)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Aug-2019
% good default toloerance: tolerance = 0.05;
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Flood fill
row = round(xy(2));
column = round(xy(1));
for i=1:3
    normX{i} = sum((X - X(row,column,i)).^2,3);
    normX{i} = mat2gray(normX{i});
    addedRegion{i} = grayconnected(normX{i}, row, column, tolerance);
    BW_band{i} = BW | addedRegion{i};
end

% Now take intersection of flood fill in each band

BW=BW_band{1} & BW_band{2} & BW_band{3};
% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end