% createNormRef.m
% Creates norm_ref structure, which stores the average reflectance value of
% each of the six colored panels for each band. The wavelength ranges of
% the bands can be altered with this script. The current values were chosen
% based on the transmittance curve generated by EVA_calibration.m.
norm_ref = struct([]);
i = 1;
for c = [10,12,2,7,1,9]
    norm_ref(i).name = lower(labs{c});
    norm_ref(i).valsR = spect(:,c);
    norm_ref(i).valsR = norm_ref(i).valsR(wl >= 661 & wl <= 669); % red band
    norm_ref(i).valsG = spect(:,c);
    norm_ref(i).valsG = norm_ref(i).valsG(wl >= 543 & wl <= 551); % green band
    norm_ref(i).valsN = spect(:,c);
    norm_ref(i).valsN = norm_ref(i).valsN(wl >= 843 & wl <= 853); % near IR band
    norm_ref(i).meanR = mean(norm_ref(i).valsR);
    norm_ref(i).meanG = mean(norm_ref(i).valsG);
    norm_ref(i).meanN = mean(norm_ref(i).valsN);
    i = i + 1;
end
save('norm_ref.mat','norm_ref');